Documentation generation: PostGIS reference, function references, ToC…
zachasme/h3-pg pull request #106
Opened 2022-11-15 08:46 UTC by mngr777

… generation

Work in progress.

* Table of contents generation moved to `generate.py`, links now work on Github;
* "PostGIS Integration" section added;
* Function cross-references ("See also: ...") added for indexing functions.

Generating table of contents and references for both extensions in single script allows to create cross-references between functions, directing users to PostGIS wrapper if it exists.
![xref](https://user-images.githubusercontent.com/1970037/201872374-6f4047c7-8c7e-4e75-892b-9e8ec2d18585.png)

Currently, a bug (?) in [Text::Markdown](https://metacpan.org/release/BOBTFISH/Text-Markdown-1.000031/source/lib/Text/Markdown.pm#L455) causes ToC generated by doctoc to be removed on PGXN:
![no-toc](https://user-images.githubusercontent.com/1970037/201871086-b6fe3df0-6da3-4de3-a32b-55e0ba1f443d.png)

Since "See also: ..." links can work either on Github or PGXN, I suggest removing ToC generation altogether and instead point users to PGXN for API reference.

2022-11-21 07:34 UTC, zachasme commented
Great work! I agree we should drop the ToC and point to PGXN. Please let me know if you need anything to progress on this.

2022-11-21 12:13 UTC, mngr777 commented
* ToC generation removed;
* more `h3_postgis` function references;
* API reference link in README points to PGXN.

2022-11-23 10:17 UTC, zachasme requested changes
Your pull request looks great! My only nit is the removal of comments, would you consider re-applying them?

2022-11-23 10:17 UTC, zachasme commented on scripts/documentation/generate.py
> -    # -- CREATE COMMENT --------------------------------------------------------
Could we keep these comment headers? I think they were helpful

2022-11-23 10:17 UTC, zachasme commented on scripts/documentation/generate.py
> -"""
I think it is useful to have a the general idea of the script documented in a comment. Could you re-insert a similar comment in the top of the file?

2022-11-23 11:49 UTC, zachasme approved these changes

2022-11-23 11:52 UTC, merged